"""Public package entry point for MiniTensor."""

from .autograd import no_grad
from .errors import DTypeError, MiniTensorError, ShapeError
from .graph import Graph, Node, Value, trace  # noqa: F401
from .nn import (
    CrossEntropyLoss,
    Dropout,
    Embedding,
    FeedForward,
    LayerNorm,
    Linear,
    LogSoftmax,
    Module,
    MSELoss,
    MultiHeadAttention,
    Parameter,
    PositionalEncoding,
    ReLU,
    Sequential,
    Softmax,
    TransformerBlock,
    cross_entropy,
    log_softmax,
    mse_loss,
    softmax,
)
from .optim import SGD, Adam, Momentum
from .tensor import (
    Tensor,
    add,
    div,
    exp,
    log,
    matmul,
    max,
    mean,
    mul,
    ones,
    pow,
    relu,
    sigmoid,
    sub,
    sum,
    tensor,
    zeros,
)

__version__ = "0.1.0"

__all__ = [
    "DTypeError",
    "Adam",
    "CrossEntropyLoss",
    "Dropout",
    "Embedding",
    "FeedForward",
    "LayerNorm",
    "Linear",
    "LogSoftmax",
    "MSELoss",
    "MiniTensorError",
    "Momentum",
    "Module",
    "MultiHeadAttention",
    "Parameter",
    "PositionalEncoding",
    "ReLU",
    "SGD",
    "Sequential",
    "Softmax",
    "ShapeError",
    "Tensor",
    "TransformerBlock",
    "__version__",
    "add",
    "cross_entropy",
    "div",
    "exp",
    "log",
    "log_softmax",
    "matmul",
    "max",
    "mean",
    "mul",
    "mse_loss",
    "no_grad",
    "ones",
    "pow",
    "relu",
    "sigmoid",
    "softmax",
    "sub",
    "sum",
    "tensor",
    "zeros",
]
